openapi: 3.0.0
info:
  title: GKash
  version: 1.0.0
  description: API documentation for authentication, user management, accounts, and transactions

servers:
  - url: https://gkash.onrender.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/register-user:
    post:
      summary: Step 1 - Register user without PIN
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_name
                - phoneNumber
                - user_nationalId
              properties:
                user_name:
                  type: string
                  example: Olive
                phoneNumber:
                  type: string
                  example: "6789087654"
                user_nationalId:
                  type: string
                  example: "12345678"
      responses:
        "201":
          description: User registered successfully. Use temp_token to set PIN
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered. Please set your PIN"
                  temp_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user_id:
                    type: string
                    example: "507f1f77bcf86cd799439011"
        "400":
          description: User already exists

  /auth/create-pin:
    post:
      summary: Step 2 - Create user PIN
      tags: [Auth]
      security:
        - tempTokenAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_pin
              properties:
                user_pin:
                  type: string
                  pattern: '^[0-9]{4}$'
                  example: "1234"
                  description: 4-digit PIN
      responses:
        "200":
          description: PIN created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "PIN created successfully"
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user:
                    type: object
                    properties:
                      user_nationalId:
                        type: string
                      user_name:
                        type: string
                      phoneNumber:
                        type: string
        "400":
          description: Invalid PIN format
        "403":
          description: Invalid temp token

  /auth/login:
    post:
      summary: Login user with PIN
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_nationalId
                - user_pin
              properties:
                user_nationalId:
                  type: string
                  example: "12345678"
                user_pin:
                  type: string
                  pattern: '^[0-9]{4}$'
                  example: "1234"
                  description: 4-digit PIN
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successful"
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user:
                    type: object
                    properties:
                      user_nationalId:
                        type: string
                      user_name:
                        type: string
                      phoneNumber:
                        type: string
        "400":
          description: Please complete registration by setting a PIN
        "401":
          description: Invalid credentials
        "404":
          description: User not found

  /user:
    get:
      summary: Get all users
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of users

  /user/{id}:
    get:
      summary: Get user by ID
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: A single user object

    put:
      summary: Update user by ID
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                phoneNumber:
                  type: string
      responses:
        "200":
          description: User updated successfully

    delete:
      summary: Delete user by ID
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: User deleted successfully

  /accounts:
    post:
      summary: Create a new account
      tags: [Accounts]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account_type
              properties:
                account_type:
                  type: string
                  enum: ["balanced fund", "fixed income fund", "money market fund", "stock market"]
                  example: balanced fund
      responses:
        "201":
          description: Account created successfully

    get:
      summary: Get all accounts for logged-in user
      tags: [Accounts]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of accounts

  /accounts/{id}:
    get:
      summary: Get account by ID
      tags: [Accounts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Account object

    delete:
      summary: Delete account by ID
      tags: [Accounts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Account deleted successfully

  /transactions:
    post:
      summary: Create a new transaction (deposit or withdraw)
      tags: [Transactions]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - transaction_type
                - amount
              properties:
                transaction_type:
                  type: string
                  enum: [deposit, withdraw]
                  example: deposit
                amount:
                  type: number
                  example: 1000
      responses:
        "201":
          description: Transaction successful

    get:
      summary: Get all transactions for authenticated user
      tags: [Transactions]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of transactions

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authenticated requests
    tempTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Temporary token for PIN setup (15-minute expiry)
