openapi: 3.0.0
info:
  title: GKash
  version: 1.0.0
  description: API documentation for authentication and user management

servers:
  - url: https://gkash.onrender.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/signup:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_name
                - phoneNumber
                - user_pin
                - user_nationalId
              properties:
                user_name:
                  type: string
                  example: Olive
                phoneNumber:
                  type: string
                  example: "6789087654"
                user_pin:
                  type: string
                  format: password
                  example: mySecretPass123
                user_nationalId:
                  type: string
                  example: "12345678"
      responses:
        '201':
          description: Signup successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: signup successful
                  token:
                    type: string
                    description: JWT token
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      user_name:
                        type: string
                      phoneNumber:
                        type: string

  /auth/login:
    post:
      summary: Login user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phoneNumber
                - user_pin
              properties:
                phoneNumber:
                  type: string
                  example: "6789087654"
                user_pin:
                  type: string
                  format: password
                  example: mySecretPass123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: login successful
                  token:
                    type: string
                    description: JWT token
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      user_name:
                        type: string
                      phoneNumber:
                        type: string

  /user:
    get:
      summary: Get all users
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    user_name:
                      type: string
                    phoneNumber:
                      type: string

  /user/{id}:
    get:
      summary: Get user by ID
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The user ID
      responses:
        '200':
          description: A single user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  user_name:
                    type: string
                  phoneNumber:
                    type: string

    put:
      summary: Update user by ID
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                phoneNumber:
                  type: string
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User updated successfully

    delete:
      summary: Delete user by ID
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User deleted successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT